### ISSUE TITLE
出现无法解析的外部符号的错误

### ISSUE THREAD

**Issue by ChenJian326** [halx99/cocos2d-x-pc-port#1]
敢问这个怎么解决
1.无法解析的外部符号 __imp__PathRelativePathToA@20，该符号在函数 "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl fsutil::to_relative(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)" (?to_relative@fsutil@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV23@_N01@Z) 中被引用	Chess	D:\CoCosStudio\Coco\Cocos\Chess\proj.win32\xxfsutility.obj
2.无法解析的外部符号 __imp__PathIsDirectoryA@4，该符号在函数 "bool __cdecl fsutil::is_dir_exists(char const *)" (?is_dir_exists@fsutil@@YA_NPBD@Z) 中被引用	Chess	D:\CoCosStudio\Coco\Cocos\Chess\proj.win32\xxfsutility.obj	是不是需要额外添加一些库还是什么

**Comment by halx99** [comment]
更新一下
